### ISSUE TITLE
Logo for Software Carbon Efficiency Rating Project

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/scer#29]
- [x] Logo for Software Carbon Efficiency Rating Project

**Comment by Jenya-design** [comment]
@seanmcilroy29 SCER logo is ready, it was earlier sent for review in [this issue](https://github.com/Green-Software-Foundation/members/issues/24) I think it's approved, there was no feedback since Nov. 
Files for SCER logo and icon [here](https://drive.google.com/drive/folders/1ost3P_JArVQQKwgcUTDNM9h-titmQ_n-?usp=drive_link)

Can I ask someone to update Projects page with relevant icons from [this folder](https://drive.google.com/drive/folders/16P78CSgeVkpnJUTz37vavPyqxx7V1o12?usp=drive_link)?
We currently have updated logos / icons for almost all projects on the page - green versions or new logos including logo for the projects in incubation 
I can prepare a separate folder with icons to use if necessary

**Comment by seanmcilroy29** [comment]
@Jenya-design - This is great, many thanks!
I'll apply the updates to the project page
